# Generated by Django 4.0.3 on 2022-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
