# Generated by Django 4.0.3 on 2022-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BooleanField(default=True),
        ),
    ]
