# Generated by Django 4.0.3 on 2022-04-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
