# Generated by Django 4.0.3 on 2022-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_client_user_alter_employee_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Alisher', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Nurzhanuly', max_length=150),
        ),
    ]
