# Generated by Django 4.0.3 on 2022-04-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
