# Generated by Django 3.0.4 on 2021-06-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210610_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpreference',
            old_name='created',
            new_name='created_at',
        ),
    ]
